apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo
data:
  DJANGO_DEBUG: "0"
  DJANGO_ALLOWED_HOSTS: "todo.local,localhost,127.0.0.1"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
