apiVersion: batch/v1
kind: Job
metadata:
  name: todo-migrate
  namespace: todo
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: baranotik/todo-web:1.0
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: todo-config
            - secretRef:
                name: todo-secrets